README.md
Updating README with usage information on how to start up the application.
=> Updating README with usage information

renovate.json
Adding renovate to the project.
=> Adding renovate to the project

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .github/workflows/ci_code.yml, saas_app/.flake8, saas_app/common/util/tests.py, saas_app/login/admin.py, saas_app/login/apps.py, saas_app/login/models.py, saas_app/login/tests.py, saas_app/login/views.py, saas_app/saas_app/settings.py, saas_app/saas_app/urls.py, saas_app/submit_request/forms.py, saas_app/submit_request/models.py, saas_app/submit_request/tests.py, saas_app/submit_request/urls.py, saas_app/submit_request/views.py, saas_app/templates/index.html, saas_app/templates/view_request.html, saas_app/user/models.py, saas_app/user/views.py
Adding github ci_code action to install dependencies, check linting and formatting, and run unit tests. 
Closes #39 
Changes made:
- Reformatted all files
- Linted all files
- Removed a few unit tests in the commont/tests folder since I realized that they were useless and were testing the wrong thing.
- Fixed up the url paths for the view saas request page
- Removed the login app since we are using a default django package
=> Adding ci_code github action plus other improvements

saas_app/saas_app/middleware.py, saas_app/saas_app/settings.py
Added a healthcheck endpoint for the service. Unit tests are coming... 😬
=> Adding a quick healthcheck for the service

.github/workflows/terraform_security_scan.yml, .github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, terragrunt/.checkov.yml, terragrunt/Makefile, terragrunt/aws/hosted_zone/outputs.tf, terragrunt/aws/hosted_zone/route53.tf, terragrunt/aws/iam/oidc_role.tf, terragrunt/env/common/common_variables.tf, terragrunt/env/common/provider.tf, terragrunt/env/staging/env_vars.hcl, terragrunt/env/staging/hosted_zone/.terraform.lock.hcl, terragrunt/env/staging/hosted_zone/terragrunt.hcl, terragrunt/env/staging/iam/.terraform.lock.hcl, terragrunt/env/staging/iam/terragrunt.hcl, terragrunt/env/terragrunt.hcl
PR includes:
- Initial project setup
- Terraform code for iam role to execute github actions
- Terraform code for hosted zone.
- Github actions for terraform plan, terraform apply and security scan
- Checkov skip file.
=> Terraform code for hosted zone, plan/apply/security scan workflow and checkov integration

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, terragrunt/aws/iam/oidc_role.tf
Creating separate roles for terraform plan and apply. Closes #65
=> Creating separate roles for terraform plan and apply

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, terragrunt/.checkov.yml, terragrunt/aws/network/outputs.tf, terragrunt/aws/network/security_groups.tf, terragrunt/aws/network/vpc.tf, terragrunt/env/staging/network/.terraform.lock.hcl, terragrunt/env/staging/network/terragrunt.hcl
Terraform code to create the VPC, VPC endpoints and security groups with Terraform for the Saas Procurement App.
=> Terraform VPC & security groups

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, terragrunt/.checkov.yml, terragrunt/aws/load_balancer/certificate.tf, terragrunt/aws/load_balancer/inputs.tf, terragrunt/aws/load_balancer/load_balancer.tf, terragrunt/aws/load_balancer/security_group.tf, terragrunt/aws/network/outputs.tf, terragrunt/aws/network/security_groups.tf, terragrunt/aws/network/vpc.tf, terragrunt/env/staging/load_balancer/.terraform.lock.hcl, terragrunt/env/staging/load_balancer/terragrunt.hcl
Terraform code for the load balancer for the Saas app. I also made some changes to the VPC and VPC security groups since I previously had items in there that were not needed. 
Disclaimer: I sort of don't know what I am doing so it could be all wrong. 😬
=> Load balancer terraform code plus some VPC adjustments

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml
Changing the order that ssm gets created since some of the iam rules have dependency of it.
=> Changing order of plan/create of ssm

terragrunt/aws/iam/iam.tf, terragrunt/aws/ssm/ssm.tf
I previously messed up the iam policy document for ssm. 
Thanks @patheard for the help!
=> Fixing up IAM policies

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, saas_app/approve/views.py, saas_app/internal_ops/views.py, saas_app/saas_app/settings.py
Closes #58.  Changes made:
- Fixed up some of the email flow since some of the emails were not going to the right recipients.
- Added a local variable in the container for local development since the settings locally and on staging are a bit different.
=> Fixing email flow & adding env variable for local development

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, terragrunt/aws/ecs/ecs.tf, terragrunt/aws/ecs/inputs.tf, terragrunt/aws/ecs/security_group.tf, terragrunt/aws/ecs/templates/saas_procurement.json.tpl, terragrunt/aws/load_balancer/load_balancer.tf, terragrunt/aws/load_balancer/outputs.tf, terragrunt/aws/load_balancer/security_group.tf, terragrunt/aws/rds/inputs.tf, terragrunt/aws/rds/outputs.tf, terragrunt/aws/rds/rds.tf, terragrunt/aws/ssm/inputs.tf, terragrunt/aws/ssm/outputs.tf, terragrunt/aws/ssm/ssm.tf, terragrunt/env/staging/ecs/terragrunt.hcl, terragrunt/env/staging/env_vars.hcl, terragrunt/env/staging/rds/terragrunt.hcl
Made a few terraform changes to make the saas app work. Major changes done:
1. Revised the RDS module to use the standard CDS terraform module
2. Revised the RDS terragrunt.hcl to not use SSM parameter since it was not needed. 
3. Revised the ssm parameter value to contain the environment variables of the app
4. Other small terraform changes. 
Hopefully, I will not break things too badly.... 🤞
=> Terraform changes to tweak Saas app infrastructure

saas_app/saas_app/settings.py, terragrunt/.checkov.yml, terragrunt/aws/ecs/ecs.tf, terragrunt/aws/ecs/inputs.tf, terragrunt/aws/ecs/security_group.tf, terragrunt/aws/hosted_zone/outputs.tf, terragrunt/aws/hosted_zone/route53.tf, terragrunt/aws/iam/iam.tf, terragrunt/aws/iam/inputs.tf, terragrunt/aws/iam/outputs.tf, terragrunt/aws/load_balancer/inputs.tf, terragrunt/aws/load_balancer/load_balancer.tf, terragrunt/aws/load_balancer/outputs.tf, terragrunt/aws/load_balancer/route53.tf, terragrunt/aws/network/security_groups.tf, terragrunt/aws/network/vpc.tf, terragrunt/aws/rds/rds.tf, terragrunt/aws/rds/security_groups.tf, terragrunt/env/staging/ecs/terragrunt.hcl, terragrunt/env/staging/iam/terragrunt.hcl, terragrunt/env/staging/load_balancer/terragrunt.hcl
Terraform changes/tweaks to get the saas app to work on AWS. I have ran the apply on all the modules in order to verify that everything is working.
=> Terraform changes for Saas App

saas_app/internal_ops/forms.py, saas_app/internal_ops/tests.py, saas_app/internal_ops/views.py
Major changes made:
- Added unit tests to test the forms in the internal ops form
- Changed the name of some of the Forms class since they were named incorrectly
- Added additional labels to some of the forms.
=> Adding more unit tests, modification of Form name and adding additional labels to forms

saas_app/approve/forms.py, saas_app/internal_ops/forms.py, saas_app/submit_request/forms.py
Closes #150 
Some of the text of selection fields gets cut off on the forms. This PR adjusts the height of the box to be auto to accommodate the text.
=> Adjust the height of selection fields

.github/workflows/build_and_deploy.yml, .github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, terragrunt/aws/ecs/ecs.tf, terragrunt/aws/ecs/inputs.tf, terragrunt/env/common/common_variables.tf, terragrunt/env/staging/env_vars.hcl, terragrunt/env/terragrunt.hcl
Adding code to forward the Saas procurement logs to Sentinel.
=> Forward logs to Sentinel

terragrunt/aws/ecs/security_group.tf
Adding descriptions to the ecs security groups to make the more user friendly.
=> Adding descritpions to the ecs security groups

saas_app/Makefile
Adds `make cov` command to show code coverage
=> feat: add code coverage make command

terragrunt/aws/ecs/ecs.tf, terragrunt/aws/iam/oidc_role.tf, terragrunt/aws/network/vpc.tf, terragrunt/aws/rds/rds.tf
Changing terraform reference links for Saas app.
=> Changing terraform reference links

saas_app/bin/initialize.sh
Neglected to originally start up the cron demon on the server and as a result cron was not running. I have now added code to start up the cron demon automatically when the initialize script is ran.
=> Start up the cron daemon

.github/workflows/build_and_deploy.yml
Small fix to try using CTR push
=> fix: use ctr to push instead of docker

.github/workflows/build_and_deploy.yml
Adds a SOCI index for the SHA image
=> fix: add soci to sha image

.devcontainer/Dockerfile
Previously, the initialize script was changed to pull out the requirements into the Dockerfile but I neglected to change the Dockerfile in the devcontainer. This PR takes care of that.
=> Changing devcontainer Dockerfile file to install packages

saas_app/bin/initialize.sh, saas_app/saas_app/settings.py, terragrunt/aws/ecs/templates/saas_procurement.json.tpl
Changes made:
- Removed the linux capabilities of the task definition since it was preventing cron from running
- Simplified the cron entry since it did have access to the environment variables
- Removed logging it to files since cron already logs that information 
- Removed cron directory creation in initialize script since the system cron already stores that information.
=> Fixing up crontab

saas_app/bin/initialize.sh, terragrunt/aws/ecs/inputs.tf, terragrunt/aws/rds/rds.tf, terragrunt/aws/ssm/README.md, terragrunt/aws/ssm/outputs.tf
Since the Saas process will most likely change, halting immediate work on this application. Changes made:
- Scaling down some resources to consume less funds
- Commented out crontab entires since we don't want the crontab to run every night.
=> Scaling down Saas app

catalog-info.yml
Setting up the catalog-info form with actual data that backstage would recognize since I totally messed it up the first time I was setting it up.
=> Changing attributes of catalog-info that backstage recognizes

.devcontainer/devcontainer.json, terragrunt/aws/ecs/ecs.tf
Changing code to use the new ECS Terraform module
=> Adding changes to use ecs module

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml
Updating the terraform and terragunt versions for the terraform apply and plan github actions
=> Updating the terraform and terragunt versions

terragrunt/aws/ecs/ecs.tf
Changing the container to not be read only file system. 
@patheard - I totally missed this in your previous thread and now have immense regrets....
=> Reverting read only file system

.github/workflows/build_and_deploy.yml
Fixing up the service name in the gihhub action since it changed.
=> Fixing up the service name in the github action

.github/workflows/build_and_deploy.yml
Fixing the service name... yet again 😞
=> Fixing again the service name

saas_app/saas_app/settings.py, saas_app/static/saas_app/css/styles.css, saas_app/templates/training/view_all_requests.html, saas_app/training_request/urls.py
Add the option to download the completed training form when viewing existing requests.
=> Add option to download form when viewing existing requests 

saas_app/training_request/views.py
Email internal ops that a training form has been submitted
=> Email internal ops when a training form has been submitted 
