cds-snc/saas-procurement

terragrunt/aws/load_balancer/inputs.tf
terragrunt/aws/load_balancer/load_balancer.tf

Originally in my terraform Load balancer code, I had the vpc_public_subnet_ids as a string but it was supposed to be a list of strings. 
Thanks @patheard for the correction!

Fixing up LB subnet type to be of type list of strings

---

saas_app/internal_ops/forms.py
saas_app/templates/internal_ops/view_all_requests.html
saas_app/templates/internal_ops/view_request.html

Hide the Purchase button until the request is approved by an S32 approver. After it is approved, then show the button. Closes #60

Hide the Purchase button until request is S32 approved

---

.github/workflows/build_and_deploy.yml

Changing the role of the github action in order for the ECS task to be able to restart.

Changing execution role of github action to be able to restart ECS

---

saas_app/internal_ops/forms.py

Fixes up an issue with the cancel button that had to be pressed twice in order to go back when you request more information or when you enter purchase information. Closes #118

Fixing cancel button bug

---

saas_app/saas_app/settings.py

Turning off DEBUG in staging since testing is no longer needed. Now DEBUG flag is turned on only in development.

Setting debug flag to true only in dev

---

saas_app/requirements.txt
saas_app/saas_app/settings.py
saas_app/saas_app/wsgi.py

Configuring project with whitenoise so that our app will be able to serve its own static files when Debug mode is false, making it a self-contained unit without relying on nginx, apache or S3. This is an issue only when Debug=False as it should be in staging and production to not display extra information. Also configured the settings file to set Debug to True in test and False in staging or production.

Configure project to use WhiteNoise to be able to server its own static files

---

saas_app/submit_request/forms.py

Fixes the code to make the currency and frequency read only after the Manager approves or denies the request.

Currency, Frequency and Fund center are read only once manager approves the form 

---

terragrunt/aws/ecs/ecs.tf

Adding a subscription filter to send all logs to Sentinel. This invokes the lambda function when a matching pattern is detected (in this case, all logs are matched).

Adding log subscription filter to sentinel forwarder

---

.gitignore

Fixed up the path of .gitignore to ignore staticfiles in the saas_app directory since it was configured incorrectly.

Fixing up the path of the staticfiles in .gitignore

---

saas_app/bin/initialize.sh

Removing sudo from starting the cron daemon since it is not needed and generates an errro.

Removing sudo from command since it is not needed

---

saas_app/saas_app/settings.py
terragrunt/aws/ecs/ecs.tf
terragrunt/aws/ecs/inputs.tf

Gave access to the environment variables of my cron job. The ECS tasks were running out of CPU and thus failing, so I had to increase the CPU cycles. To counteract the cost of this (approximately $30 increase in cost/month), I decreased the ECS task to 1. With the proceeding changes, the cost should be the same.

Adding env access to crontab, increasing fargate CPU and decreasing ECS task to 1

---

terragrunt/aws/ecs/inputs.tf

Uggh... So my terraform apply failed (https://github.com/cds-snc/saas-procurement/actions/runs/5648087651/job/15299536819) because I can't have an ECS task with 1G cpu and 1GB memory - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html. I would have to increase the memory to 2GB but as this will increase the cost and I have minimized the ecs tasks to 1, I am hoping that this will be sufficient.  Sorry, hopefully this will be the last one!

Changing CPU (again)

---

saas_app/Dockerfile
saas_app/bin/initialize.sh
saas_app/saas_app/settings.py
terragrunt/aws/load_balancer/load_balancer.tf

Changes made:
- Pulled upgrading pip and installing requirements out of initialize file and into the Dockerfile.
- Adjusted the healthcheck to interval of 60 seconds and timeout of 30 seconds
- Adjusted the command to start the cron

Docker and Healthcheck adjustments

---

saas_app/approve/forms.py
saas_app/internal_ops/forms.py
saas_app/internal_ops/tests.py
saas_app/internal_ops/views.py
saas_app/submit_request/forms.py
saas_app/submit_request/tests.py
saas_app/templates/approve/view_all_prev_requests.html
saas_app/templates/approve/view_all_requests.html
saas_app/templates/detail.html
saas_app/templates/index.html
saas_app/templates/internal_ops/view_all_prev_requests.html
saas_app/templates/internal_ops/view_all_requests.html
saas_app/templates/request/saas_request.html
saas_app/templates/request/view_all_requests.html

The following changes were made:
1. The links to the documents when you submit the form were taken off
2. Links are no longer opening on new tabs
3. For the internal ops view, the submit button for S32 approval now saves the form and notifies the user if the fund centre or S32 approver is not added.
4. The Fund center box was made bigger to fit the data.
5. The info requested and date requested fields only show up if there is data. 
6. The Name field in the saas request form was renamed to Name of Saas 
7. The currency and frequency were made read only when viewing a submitted saas.

Internal Ops changes as requested

---

terragrunt/aws/iam/iam.tf

Added IAM role so that we can use Amazon ECS exec for debugging purposes. More information can be found here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html
Let me know if granting this is not secure or if there is a better way to do it. It is super useful though, when trying to debug your container in ECS.

Iam Role for ECS exec commands

---

.github/workflows/build_and_deploy.yml

Closes #237. 
Fixing up platform linux platform SBOM architecture to be amd64 from arm64. This would fix up the issue that is displayed here - https://github.com/cds-snc/saas-procurement/actions/runs/6006361213/job/16290758265

Fixing up generating Docker SBOM platform

---

terragrunt/aws/rds/rds.tf

In order to save money, I am reverting to the default db.t3.medium instance_class as opposed to the serverless one as it is 3 times more expensive 😱 
By removing the instance class, we are defaulting to the terraform-modules rds instance class of db.t3.medium

Removing the serverless instance_class to be the default db.t3.medium

---

catalog-info.yml

Add backstage config file to the saas procurement app to be able to ingest github data into Backstage.

Adding backstage catalog info config file to be able to read github data to Backstage

---

catalog-info.yml

Adding owner to the config file - the documentation does not state that it is required but apparently it is!

Adding owner to the config file

---

saas_app/internal_ops/forms.py
saas_app/templates/internal_ops/view_request.html

In Bootstrap 5, there have been some changes to the way the modals were named/created and this PR fixes those difference. The reason why the modals broke in the first place was due to the fact that we were previously using Bootstrap 4 and now we are using Bootsrap 5. The modals look like this:

Fixing modals that broke due to upgrade of Bootstrap 5

---

saas_app/Dockerfile

Upgrading setup tools to latest version in order to avoid the security vulnerability listed here - https://github.com/cds-snc/saas-procurement/security/dependabot/5
After upgrade, the current version is listed below:

Upgrading setuptools to latest version to avoid security vulnerability
